name: abergymmobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  nfc_manager: ^3.2.0
  permission_handler: ^10.2.0
  mysql_client: ^0.0.27
  page_transition: ^2.0.9
  flutter_launcher_icons: ^0.11.0
  shared_preferences: ^2.0.15

flutter_icons:
  image_path_android: "assets/images/icon.png"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
