name: abergymmobile
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mysql1: ^0.20.0
  mysql_client: ^0.0.27
  flutter_launcher_icons: "^0.10.0"
  flutter_native_splash: ^2.2.14

flutter_native_splash:
  color: "#252532"
  image: assets/images/icon.png

flutter_icons:
  image_path_android: "assets/images/icon.png"
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
