name: abergymmobile
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mysql_client: ^0.0.27
  flutter_launcher_icons: "^0.10.0"
  page_transition: ^2.0.9
  shared_preferences: ^2.0.17
  simple_animations: ^3.0.0
  flutter_native_splash: ^2.2.16
  permission_handler: ^10.2.0
  qr_code_scanner: ^1.0.1

flutter_native_splash:
  image: assets/images/icon.png
  color: "#252532"

flutter_icons:
  image_path_android: "assets/images/icon.png"
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
